GET http://localhost:5000/users
content-type: application/json

###
GET http://localhost:5000/users/mjopp0@merriam-webster.com 

###
POST http://localhost:5000/login
Content-Type: application/json
Content-Length: 70

{
"email": "lvearnals5@sina.com.cn",
"Password": "3sNXRgyZ0"
}

###
POST http://localhost:5000/create
Content-Type: application/json

{
    "Id": 2,
    "first_name": "Monty",
    "last_name": "Jopp",
    "email": "mjopp0@merriam-webster.com",
    "gender": "Male",
    "Password": "uehSLnl"
}